name: Release
on:
  push:
    tags:
      - '*'
  schedule:
    # Run every day at 02:23
    - cron: '23 2 * * *'
  workflow_dispatch:

jobs:
  phar:
    name: Compile PHAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2

      # Compile PHAR
      - name: Install box
        run: composer global require --dev --no-progress humbug/box
      - name: Install Composer dependencies
        run: composer update --no-progress
      - name: Compile PHAR
        run: box compile --with-docker

      # Upload compiled PHAR as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: phar
          path: |
            .build/cache-warmup.phar
            Dockerfile

  docker:
    name: Docker deploy
    runs-on: ubuntu-latest
    needs: phar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Download PHAR and Dockerfile
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: phar
      - name: Make PHAR executable
        run: chmod +x .build/cache-warmup.phar

      # Generate metadata
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: eliashaeussler/cache-warmup
          tags: |
            type=raw,value=latest,enable=false
            type=semver,pattern={{version}}
            type=raw,value=${{ github.ref_name }},enable=${{ github.event_name == 'workflow_dispatch' }}

      # Prepare build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login at Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

  # Job: Create release
  release:
    name: Create release
    if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: phar
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Check if tag is valid
      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$ ]]; then
            exit 1
          fi

      # Download PHAR
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: phar
      - name: Make PHAR executable
        run: chmod +x .build/cache-warmup.phar

      # Sign PHAR file
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PHAR_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHAR_GPG_PASSPHRASE }}
      - name: Sign PHAR file
        run: gpg --armor --output .build/cache-warmup.phar.asc --yes --detach-sig .build/cache-warmup.phar

      # Create release
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            .build/cache-warmup.phar
            .build/cache-warmup.phar.asc
